# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pm < Formula
  desc "Superlight process manager"
  homepage "https://github.com/rusintez/pm"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rusintez/pm/releases/download/v0.1.0/pm_darwin_amd64.tar.gz"
      sha256 "6d76f92174b392600a04b6d4f88423f97e03fd3e7c52c83bd747e2d3fdb63adb"

      define_method(:install) do
        bin.install "pm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rusintez/pm/releases/download/v0.1.0/pm_darwin_arm64.tar.gz"
      sha256 "70f84111f4a0d98e0f4a9725c902dcb9573a1e2c6df56b9a42a8f057da4d1379"

      define_method(:install) do
        bin.install "pm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusintez/pm/releases/download/v0.1.0/pm_linux_amd64.tar.gz"
      sha256 "edb64e7f18b278677e91b3f5c3b6318ec7b5ae37cf374cfb6b21f8a417825ee3"
      define_method(:install) do
        bin.install "pm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusintez/pm/releases/download/v0.1.0/pm_linux_arm64.tar.gz"
      sha256 "13da4fe196f5db5474d296026f3843b3591a3fde4b65863b7ab523d9842b6d8e"
      define_method(:install) do
        bin.install "pm"
      end
    end
  end
end
